# ~/.config/hypr/autostart.conf

exec = hyprctl dispatch workspace 1
exec = hyprctl dispatch movetoworkspace 1,eDP-1
exec = hyprctl dispatch workspace 2
exec = hyprctl dispatch movetoworkspace 2,eDP-1
exec = hyprctl dispatch workspace 3
exec = hyprctl dispatch movetoworkspace 3,eDP-1
exec = hyprctl dispatch workspace 4
exec = hyprctl dispatch movetoworkspace 4,eDP-1
exec = hyprctl dispatch workspace 5
exec = hyprctl dispatch movetoworkspace 5,eDP-1
exec = hyprctl dispatch workspace 6
exec = hyprctl dispatch movetoworkspace 6,eDP-1
exec = hyprctl dispatch workspace 7
exec = hyprctl dispatch movetoworkspace 7,eDP-1

# Temporarily disabled while investigating long video-call GPU instability.
# exec-once = flatpak run org.ferdium.Ferdium
