# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# =============================
# Steam (ALL windows controlled)
# =============================

windowrule {
    name = steam-all
    match:class = ^steam.*$
    workspace = 1
    float = on
    center = on
}

windowrule {
    name = steam-title-fallback
    match:title = ^(Steam|Updating|Working|Loading).*
    workspace = 1
    float = on
    center = on
}

# =============================
# Dota 2 (launched via Steam)
# =============================

windowrule {
    name = dota2-main
    match:class = ^(steam_app_570|dota2)$
    workspace = 1
    fullscreen = on
    no_anim = on
}

# -----------------------------
# Pointer configuration (example)
# -----------------------------
device {
    name = logitech-g300s-optical-gaming-mouse
    sensitivity = 0.20
    accel_profile = adaptative
}

